name: 'Delete Artifact and Caches every 3rd day'

on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          expire-in: 0 # Set this to 0 to delete all artifacts - which are 0 days old
          
  clear-cache:
    runs-on: ubuntu-latest
    needs: delete-artifacts
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: 'true'
