name: Create resources using Terraform
 
on:
  push:
    branches: 
      - main
     
jobs:

  tflint-checks:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout Repository
    - name : Check out Git Repository
      uses: actions/checkout@v3  
      
    # TFLint - Terraform Check
    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}
        
    # Print TFLint version
    - name: Show version
      run: tflint --version
      
    # Install plugins
    - name: Init TFLint
      run: tflint --init
      
    # Run tflint command in each directory recursively
    - name: Run TFLint
      run: tflint -f compact --recursive
      
   
  tfsec-checks:
      runs-on: ubuntu-latest
      needs: tflint-checks
      
      steps:
      # Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v2
      
      # Tfsec - Security scanner for your Terraform code
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
          

         
          
